# Generated by Django 4.2.4 on 2023-10-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
